declare module 'bitcore-explorers' {
  /** Declaration file generated by dts-gen */

  export class Insight {
    constructor(url: any, network: any);

    address(address: any, callback: any): any;

    broadcast(transaction: any, callback: any): any;

    getUnspentUtxos(addresses: any, callback: any): any;

    requestGet(path: any, callback: any): void;

    requestPost(path: any, data: any, callback: any): void;
  }
}
